module.exports = {
  currencies: {
    MXN: 'mxn',
    ARS: 'ars',
    BTC: 'btc',
    ETH: 'eth',
    XRP: 'xrp',
    LTC: 'ltc',
    BCH: 'bch',
    TUSD: 'tusd',
    BAT: 'bat',
    DAI: 'dai',
    GNT: 'gnt',
    MANA: 'mana',
  },
  exchanges: {

    BTC_ETH: 'eth_btc',
    BTC_XRP: 'xrp_btc',
    BTC_LTC: 'ltc_btc',
    BTC_BCH: 'bch_btc',
    BTC_TUSD: 'tusd_btc',
    BTC_MANA: 'mana_btc',
    BTC_GNT: 'gnt_btc',
    BTC_BAT: 'bat_btc',
    BTC_DAI: 'btc_dai',
    MXN_BTC: 'btc_mxn',
    MXN_ETH: 'eth_mxn',
    MXN_XRP: 'xrp_mxn',
    MXN_LTC: 'ltc_mxn',
    MXN_BCH: 'bch_mxn',
    MXN_TUSD: 'tusd_mxn',
    MXN_MANA: 'mana_mxn',
    MXN_GNT: 'gnt_mxn',
    MXN_BAT: 'bat_mxn',
    MXN_DAI: 'dai_mxn',
    ARS_BTC: 'btc_ars',
  },
  ledgers: {
    TRADES: 'trades',
    FEES: 'fees',
    FUNDINGS: 'fundings',
    WITHDRAWLS: 'withdrawals',
  },
};
